// CUDA backend aggregation translation unit.
// Module files are included in source order so helpers, templates, and internal linkage keep the same semantics as the former monolithic file.
#include "modules/runtime_common.cu"
#include "modules/elementwise_kernels.cu"
#include "modules/reduction_loss_optim_kernels.cu"
#include "modules/nn_shape_fused_kernels.cu"
#include "modules/memory_api.cu"
#include "modules/matmul_api.cu"
#include "modules/elementwise_api.cu"
#include "modules/reduction_loss_api.cu"
#include "modules/optim_api.cu"
#include "modules/nn_api.cu"
#include "modules/shape_cache_attention_api.cu"
#include "modules/fused_rope_api.cu"
#include "modules/cnn_pool_api.cu"
